# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mediawiki-gateway"
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jani Patokallio"]
  s.date = "2014-01-26"
  s.description = ""
  s.email = "jpatokal@iki.fi"
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    ".ruby-version",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README",
    "Rakefile",
    "config/hosts.yml",
    "lib/media_wiki.rb",
    "lib/media_wiki/config.rb",
    "lib/media_wiki/exception.rb",
    "lib/media_wiki/gateway.rb",
    "lib/media_wiki/utils.rb",
    "mediawiki-gateway.gemspec",
    "samples/README",
    "samples/create_page.rb",
    "samples/delete_batch.rb",
    "samples/download_batch.rb",
    "samples/email_user.rb",
    "samples/export_xml.rb",
    "samples/get_page.rb",
    "samples/import_xml.rb",
    "samples/run_fake_media_wiki.rb",
    "samples/search_content.rb",
    "samples/semantic_query.rb",
    "samples/upload_commons.rb",
    "samples/upload_file.rb",
    "spec/fake_media_wiki/api_pages.rb",
    "spec/fake_media_wiki/app.rb",
    "spec/fake_media_wiki/query_handling.rb",
    "spec/gateway_spec.rb",
    "spec/import-test-data.xml",
    "spec/spec_helper.rb",
    "spec/utils_spec.rb"
  ]
  s.homepage = "http://github.com/jpatokal/mediawiki-gateway"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Connect to the mediawiki API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 1.3.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<sham_rack>, [">= 0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3"])
      s.add_development_dependency(%q<debugger>, [">= 0"])
      s.add_development_dependency(%q<sinatra>, [">= 0"])
      s.add_development_dependency(%q<activemodel>, [">= 0"])
    else
      s.add_dependency(%q<rest-client>, [">= 1.3.0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sham_rack>, [">= 0"])
      s.add_dependency(%q<rr>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 1.3"])
      s.add_dependency(%q<debugger>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<activemodel>, [">= 0"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 1.3.0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sham_rack>, [">= 0"])
    s.add_dependency(%q<rr>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 1.3"])
    s.add_dependency(%q<debugger>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<activemodel>, [">= 0"])
  end
end

